# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Develop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': '\u5f00\u53d1\u4e3b\u673a\u7ec4\u4fe1\u606f',
                'verbose_name_plural': '\u5f00\u53d1\u4e3b\u673a\u7ec4\u4fe1\u606f\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='HostList_Develop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='\u7269\u7406\u673aIP\u5730\u5740')),
                ('manage_ip', models.GenericIPAddressField(unique=True, verbose_name='\u7ba1\u7406IP\u5730\u5740')),
                ('hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('application', models.CharField(max_length=20, verbose_name='\u5e94\u7528')),
                ('bianhao', models.CharField(max_length=30, verbose_name='\u7f16\u53f7')),
                ('idc_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u6240\u5c5e\u673a\u623f')),
                ('group', models.ManyToManyField(blank=True, to='app.Group_Develop', verbose_name='\u7ec4\u540d')),
            ],
            options={
                'verbose_name': '\u5f00\u53d1\u4e3b\u673a\u5217\u8868',
            },
        ),
        migrations.AlterField(
            model_name='newuser',
            name='manage_role',
            field=models.CharField(choices=[(b'super', '\u8d85\u7ea7\u7ba1\u7406\u5458'), (b'manage', '\u7ba1\u7406\u5458')], max_length=30, verbose_name='\u89d2\u8272'),
        ),
    ]
