# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_group_test_hostlist_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostList_Pre_Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='\u7269\u7406\u673aIP\u5730\u5740')),
                ('manage_ip', models.GenericIPAddressField(unique=True, verbose_name='\u7ba1\u7406IP\u5730\u5740')),
                ('hostname', models.CharField(max_length=30, verbose_name='\u4e3b\u673a\u540d')),
                ('application', models.CharField(max_length=20, verbose_name='\u5e94\u7528')),
                ('bianhao', models.CharField(max_length=30, verbose_name='\u7f16\u53f7')),
                ('idc_name', models.CharField(blank=True, max_length=40, null=True, verbose_name='\u6240\u5c5e\u673a\u623f')),
                ('group', models.ManyToManyField(blank=True, to='app.Group_Test', verbose_name='\u7ec4\u540d')),
            ],
            options={
                'verbose_name': '\u9884\u53d1\u5e03\u4e3b\u673a\u5217\u8868',
            },
        ),
    ]
