# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_containslist_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainsList_Pre_Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contain_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5bb9\u5668ID')),
                ('contain_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP\u5730\u5740')),
                ('contain_netmask', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5bb9\u5668\u63a9\u7801')),
                ('contain_port', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5bb9\u5668\u76d1\u542c\u7aef\u53e3')),
                ('contain_http', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u670d\u52a1url')),
                ('create_datetime', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5bb9\u5668\u521b\u5efa\u65f6\u95f4')),
                ('contain_cpu_core', models.CharField(blank=True, max_length=10, null=True, verbose_name='cpu\u7ed1\u5b9a\u6838\u53f7')),
                ('contain_host', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u7269\u7406\u673a\u4e3b\u673a\u540d')),
                ('contain_memory', models.CharField(blank=True, max_length=10, null=True, verbose_name='\u5185\u5b58\u5206\u914d')),
                ('contain_hostname', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5bb9\u5668\u4e3b\u673a\u540d')),
                ('release_application', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5e94\u7528\u540d\u79f0')),
                ('service_pack', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5e94\u7528\u5305\u540d')),
                ('service_depend', models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5e94\u7528\u4f9d\u8d56')),
                ('service_env', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u670d\u52a1\u73af\u5883')),
                ('project_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('proposer', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u9879\u76ee\u5f00\u53d1\u8005')),
                ('principal', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u9879\u76ee\u8d1f\u8d23\u4eba')),
                ('project_section', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u9879\u76ee\u6240\u5c5e\u90e8\u95e8')),
                ('state', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5bb9\u5668\u72b6\u6001')),
                ('flag', models.CharField(blank=True, max_length=5, null=True, verbose_name='\u5bb9\u5668\u6807\u8bb0\u4f4d')),
                ('x_flag', models.CharField(blank=True, max_length=30, null=True, verbose_name='\u5bb9\u5668\u5904\u7406\u60c5\u51b5')),
            ],
            options={
                'verbose_name': '\u9884\u751f\u4ea7\u73af\u5883\u5bb9\u5668\u5217\u8868',
                'verbose_name_plural': '\u9884\u751f\u4ea7\u73af\u5883\u5bb9\u5668\u5217\u8868',
            },
        ),
    ]
