# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_containslist_pre_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containslist_develop',
            name='contain_ip',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='IP\u5730\u5740'),
        ),
    ]
